# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-11-06T13:50:30Z"
  labels:
    app: industria-dataflow
  name: industria-dataflow
spec:
  containers:
  - image: localhost/data:latest
    name: data
    ports:
    - containerPort: 8000
      hostPort: 8000
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - mountPath: /data
      name: industria-data-pvc
  - args:
    - nginx
    - -g
    - daemon off;
    image: localhost/front:latest
    name: front
  - image: localhost/model:latest
    name: model
    volumeMounts:
    - mountPath: /data
      name: industria-data-pvc
  - image: localhost/api:latest
    name: api
    volumeMounts:
    - mountPath: /data
      name: industria-data-pvc
  volumes:
  - name: industria-data-pvc
    persistentVolumeClaim:
      claimName: industria-data
